community_list_item:
  class: sfDoctrineRouteCollection
  options:
    model:                CommunityListItem
    module:               community_list_item
    prefix_path:          community_list_item
    column:               id
    with_wildcard_routes: true

community_list:
  class: sfDoctrineRouteCollection
  options:
    model:                CommunityList
    module:               community_list
    prefix_path:          community_list
    column:               id
    with_wildcard_routes: true

plugin_category:
  class: sfDoctrineRouteCollection
  options:
    model:                PluginCategory
    module:               plugin_category
    prefix_path:          plugin_category
    column:               id
    with_wildcard_routes: true

plugin_author:
  class: sfDoctrineRouteCollection
  options:
    model:                PluginAuthor
    module:               plugin_author
    prefix_path:          plugin_author
    column:               id
    with_wildcard_routes: true

symfony_plugin:
  class: sfDoctrineRouteCollection
  options:
    model:                SymfonyPlugin
    module:               symfony_plugin
    prefix_path:          symfony_plugin
    column:               id
    with_wildcard_routes: true

post_post:
  class: sfDoctrineRouteCollection
  options:
    model:               Post
    module:              post
    prefix_path:         post
    column:              id
    with_wildcard_routes: true

page_page:
  class: sfDoctrineRouteCollection
  options:
    model:               Page
    module:              page
    prefix_path:         page
    column:              id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: symfony_plugin, action: index }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

default_index:
  url:   /login
  param: { module: sfGuardAuth, action: signin }  

default:
  url:   /:module/:action/*
