rendering:                            ~
security:                             ~

# insert your own filters here
csNavigation:
  class: csNavigationFilter

cache:                                ~
common:                               ~
execution:                            ~
