rendering: ~
security:
  class: sfGuardBasicSecurityFilter

# insert your own filters here
csNavigation:
  class: csNavigationFilter
  
sf_google_analytics_plugin:
  class: sfGoogleAnalyticsFilter

cache:     ~

execution: ~