navigation:
  Main:
    Plugins:      @homepage
    Categories:   @plugin_categories
    Developers:   @authors
  Footer:
    home:         /
    about:        /about
    contact:      /contact
        
settings:
  database:
    driven:    on