navigation:
  Main:
    Home:         @homepage
    Plugins:      @plugins
    Categories:   @plugin_categories
    Developers:   @authors

  Footer:
    home:         '/'
    about:        @about
    contact:      @contact

  # Secondary:
    report a bug: 'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new'
    feedback:     'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new'
    
settings:
  database:
    driven:    on