navigation:
  Main:
    Home:         @homepage
    Plugins:      @plugins
    Categories:   @plugin_categories
    Developers:   
      ~route:     @authors
      create:     @author_new
  Footer:
    home:         '/'
    about:        @about
    contact:      @contact
    signin:       @signin
        
settings:
  database:
    driven:    on