navigation:
  Main:
    Home:         @homepage
    Plugins:      @plugins
    Categories:   @plugin_categories
    Developers:   @authors
  Footer:
    home:         '/'
    about:        @about
    contact:      @contact
        
settings:
  database:
    driven:    on