navigation:
  Main:
    Home:             @homepage
    Browse Plugins:      @plugins
    Submit A Plugin:         @plugin_categories
    Browse Developers:   @authors
    Lists:        @community_lists

  Footer:
    Home:                 '/'
    About SympLIST:        @about
    Feedback:              @contact
    Contact:              'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new'

    
settings:
  database:
    driven:    true