navigation:
  Main:
    Home:         @homepage
    Plugins:      @plugins
    Categories:   @plugin_categories
    Developers:   @authors
  Footer:
    home:         '/'
    about:        @about
    blog:         'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new'
    contact:      @contact
    report a bug: 'http://github.com/bshaffer/Symplist/issues'
  Secondary:
    report a bug: 'http://github.com/bshaffer/Symplist/issues'
    blog:         'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new'
    
settings:
  database:
    driven:    on