navigation:
  Main:
    Home:               @homepage
    Plugins:      @plugins
    Developers:   @authors
    Lists:        @community_lists

  Footer:
    Home:                 '/'
    About SympLIST:        @about
    Contact:              @contact
    Feedback:              'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new'

    
settings:
  database:
    driven:    true