plugins:
  url:                                /plugins
  param:                              { module: plugin, action: list }

plugin_categories:
  url:                                /plugins/categories
  param:                              { module: plugin, action: categories }

plugins_by_category:
  url:                                /plugins/categories/:slug
  param:                              { module: plugin, action: byCategory }

plugin_new:
  url:                                /plugins/new
  param:                              { module: plugin, action: new }

plugin:
  url:                                /plugins/:title
  param:                              { module: plugin, action: show }

plugin_register:
  url:                                /plugins/:title/register
  param:                              { module: plugin, action: register }

authors:
  url:                                /authors
  param:                              { module: author, action: index }

author:
  url:                                /authors/:username
  param:                              { module: author, action: show }

author_new:
  url:                                /author/new
  param:                              { module: author, action: join }
  
author_edit:
  url:                                /author/:username/edit
  param:                              { module: author, action: edit }

about:
  url:                                /about
  param:                              { module: site, action: about }

contact:
  url:                                /contact
  param:                              { module: site, action: contact }

signin:
  url:                                /signin
  param:                              { module: sfGuardAuth, action: signin }

signout:
  url:                                /signout
  param:                              { module: sfGuardAuth, action: signout }

signout_redirect:
  url:                                /signout/redirect
  param:                              { module: site, action: signoutRedirect }

# default rules
homepage:
  url:                                /
  param:                              { module: plugin, action: index }

default_index:
  url:                                /:module
  param:                              { action: index }

default:
  url:                                /:module/:action/*
