# Plugins

plugins:
  url:                                /plugins
  param:                              { module: plugin, action: list }

plugin_categories:
  url:                                /plugins/categories
  param:                              { module: plugin, action: categories }

plugins_by_category:
  url:                                /plugins/categories/:slug
  param:                              { module: plugin, action: byCategory }

plugin_register:
  url:                                /plugins/new
  param:                              { module: plugin, action: register }

plugins_view_all:
  url:                                /plugins/all
  param:                              { module: plugin, action: index }

plugin_rate_ajax:
  url:                                /plugins/rate
  param:                              { module: plugin, action: rate }  

plugin_search:
  url:                                /plugins/search
  params:                             { module: plugin, action: search }
  requirements:
    sf_method:                        POST
  
plugin:
  url:                                /plugins/:title
  param:                              { module: plugin, action: show }

plugin_claim:
  url:                                /plugins/:title/claim
  param:                              { module: plugin, action: claim }

plugin_edit:
  url:                                /plugins/:title/edit
  param:                              { module: plugin, action: edit }

plugin_rate:
  url:                                /plugins/:title/rate/:rating
  param:                              { module: plugin, action: rate }  
  requirements:                       { rating: \d+ }

plugin_autocomplete:
  url:                                /plugins/search/auto
  params:                             { module: plugin, action: autocomplete }

plugin_autocomplete_home:
  url:                                /plugins/search/auto/full
  params:                             { module: plugin, action: homeAutocomplete }

# Lists

community_lists:
  url:                                /lists
  params:                             { module: list, action: index }

list_rate_ajax:
  url:                                /lists/rate
  param:                              { module: list, action: rate }  

list_item_add_ajax:
  url:                                /lists/item/add
  param:                              { module: list, action: addListItemAjax }
  
list_create:                          
  url:                                /lists/create
  param:                              { module: list, action: create }
  
community_list:
  class:                              sfDoctrineRoute
  url:                                /lists/:slug
  param:                              { module: list, action: show }
  options:                            { type: object, model: CommunityList }

community_list_edit:
  class:                              sfDoctrineRoute
  url:                                /lists/:slug/edit
  param:                              { module: list, action: edit }
  options:                            { type: object, model: CommunityList }

community_list_item_edit:
  class:                              sfDoctrineRoute
  url:                                /lists/:slug/item/:id/edit
  param:                              { module: list, action: editItem }
  options:                            { type: object, model: CommunityListItem }
  requirements:                       { sf_method: [GET, POST] }

community_list_add_item:
  url:                                /lists/:slug/item/add
  param:                              { module: list, action: addListItem }

# Profiles

authors:
  url:                                /authors
  param:                              { module: author, action: index }

author:
  url:                                /authors/:username
  param:                              { module: author, action: show }

author_new:
  url:                                /author/new
  param:                              { module: author, action: join }
  
author_edit:
  url:                                /author/:username/edit
  param:                              { module: author, action: edit }

about:
  url:                                /about
  param:                              { module: site, action: about }

contact:
  url:                                /contact
  param:                              { module: site, action: contact }

signin:
  url:                                /signin
  param:                              { module: sfGuardAuth, action: signin }

signout:
  url:                                /signout
  param:                              { module: sfGuardAuth, action: signout }

signout_redirect:
  url:                                /signout/redirect
  param:                              { module: site, action: signoutRedirect }

# default rules
homepage:
  url:                                /
  param:                              { module: site, action: index, homepage: true }

default_index:
  url:                                /:module
  param:                              { action: index }

default:
  url:                                /:module/:action/*
