default:
  http_metas:
    content-type:                     text/html

  metas:
    #title:                           symfony project
    #description:                     symfony project
    #keywords:                        symfony, project
    #language:                        en
    #robots:                          index, follow

  stylesheets:                        [ reset.css, text.css, 960.css, custom.css, jquery.autocomplete.css ]

  javascripts:                        ['http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js', jquery.infieldlabel.min.js, jquery.rating.pack.js, jquery.autocomplete.js, theme.js]

  has_layout:                         true
  layout:                             layout
