default:
  http_metas:
    content-type:                     text/html

  metas:
    title:                           sympLIST - Symfony Plugin Directory
    description:                     sympLIST is a community-oriented site for finding high quality Symfony plugins and developers for your web apps.
    keywords:                        symfony, plugins, developers, nashville, brent shaffer
    #language:                        en
    robots:                          index, follow

  stylesheets:                        [ reset.css, text.css, 960.css, custom.css, jquery.autocomplete.css ]

  javascripts:                        ['http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js', jquery.infieldlabel.min.js, jquery.rating.pack.js, jquery.autocomplete.js, theme.js]

  has_layout:                         true
  layout:                             layout
