default:
  http_metas:
    content-type:                     text/html

  metas:
    #title:                           symfony project
    #description:                     symfony project
    #keywords:                        symfony, project
    #language:                        en
    #robots:                          index, follow

  stylesheets:                        [ reset.css, text.css, 960.css, main.css, frontend.css, rateable.css ]

  javascripts:                        [jquery]

  has_layout:                         on
  layout:                             layout
