SymfonyPlugin:
  actAs:                              
    Sluggable: ~
    Timestampable: ~
    myLuceneDoctrineTemplate: ~
    Attachable:   { types: [Image] }
    Commentable:  []
  columns:
    title:                            
      type:                           string(255)
      unique:                         true
      notnull:                        true
    description:                      clob
    symfony_developer:                string(255)
    category_id:                      integer
    active:                           boolean
    repository:                       string(255)
    image:                            string(255)
    homepage:                         string(255)
    ticketing:                        string(255)
    featured:                         boolean
    symplist_index:
      type:                           decimal(3,1)
  relations:
    Tags:
      class:                          Tag
      foreignAlias:                   Plugins
      local:                          plugin_id
      refClass:                       PluginTag
    Authors:
      class:                          sfGuardUser
      local:                          plugin_id
      foreign:                        author_id
      refClass:                       SymfonyPluginAuthor
      foreignAlias:                   Plugins
    Raters:
      class:                          sfGuardUser
      refClass:                       PluginRating
      foreignAlias:                   RatedPlugins
    PluginCategory:
      alias:                          Category
      foreignAlias:                   Plugins
      local:                          category_id

SymfonyPluginAuthor:
  actAs:    [Timestampable]
  options:
    symfony:
      form: false
      filter: false
  columns:
    plugin_id:
      type:                           integer
      notnull:                        true
    author_id:
      type:                           integer(4)
      notnull:                        true
  relations:
    Plugin:
      class:                          SymfonyPlugin
      local:                          plugin_id
      onDelete:                       CASCADE
    Author:
      class:                          sfGuardUser
      local:                          author_id
      onDelete:                       CASCADE

PluginRating:
  actAs:    [Timestampable]
  columns:
    symfony_plugin_id:  integer
    sf_guard_user_id:   integer(4)
    rating:             integer
  relations:  
    SymfonyPlugin:
      alias:        Plugin
      foreignAlias: Ratings
      # local:        plugin_id
      onDelete:     CASCADE
    sfGuardUser:
      alias:          User
      foreignAlias:   Ratings
      # local:          user_id
      onDelete:     CASCADE        

PluginAuthor:
  actAs:    [Timestampable]
  columns:
    first_name:                 string(255)
    last_name:                  string(255)
    email:                      string(255)
    bio:                        clob
    sf_guard_user_id:           integer(4)
  relations:
    sfGuardUser:
      alias:                          User
      foreignAlias:                   Author
      type:                           one
      foreignType:                    one

PluginCategory:
  actAs:
    Timestampable:  ~
    Sluggable:      ~
  columns:
    name:                       string(255)
    description:                clob

Tag:
  actAs:                        [Timestampable]
  columns:
    name:                       string(255)
    description:                clob

PluginTag:
  actAs:                        [Timestampable]
  options:
    symfony:
      form:                     false
      filter:                   false
  columns:
    tag_id:
      notnull:                  true
      type:                     integer
    plugin_id:
      notnull:                  true
      type:                     integer
  relations:
    Tag:
      foreignAlias:             PluginTags
      onDelete:                 CASCADE
    Plugin:
      class:                    SymfonyPlugin
      local:                    plugin_id
      foreignAlias:             PluginTags
      onDelete:                 CASCADE

PluginRelease:
  actAs:
    Timestampable:          ~
    Sortable:
      uniqueBy:             [plugin_id]
  columns:
    plugin_id:
      type:                 integer
      notnull:              true
    version:
      type:                 string(10)
    date:   timestamp
    summary:                clob
    stability:
      type:                 enum
      values:               [alpha, beta, stable]
    readme:                 clob
  relations:
    SymfonyPlugin:
      alias:                Plugin
      foreignAlias:         Releases
      local:                plugin_id
      onDelete:             CASCADE
    ApiVersions:
      class:                SymfonyApiVersion
      refClass:             PluginReleaseSymfonyApiVersion
      local:                release_id
      foreign:              api_version_id

PluginReleaseDependency:
  actAs:                    [Timestampable]
  columns:
    release_id:
      type:                 integer
      notnull:              true
    dependency_id:
      type:                 integer
      notnull:              true
    dependency_version_min:
      type:                 string(255)
    dependency_version_max:
      type:                 string(255)
  relations:
    Release:
      class:                PluginRelease
      foreignAlias:         Dependencies
      local:                release_id
      onDelete:             CASCADE
    Dependency:
      class:                SymfonyPlugin
      foreignAlias:         DependentReleases
      local:                dependency_id
      onDelete:             CASCADE
      
CommunityList:
  actAs: 
    Timestampable: ~
    Sluggable: ~
    Markdown:
      fields: [description]
  columns:
    title: 
      type:         string(255)
      notnull:      true
    description:    clob
    featured:       boolean
    submitted_by:   
      type:         integer(4)
      notnull:      true
  relations:
    User:
      class:            sfGuardUser
      foreignAlias:     CommunityListItems
      local:            submitted_by
    
CommunityListItem:
  actAs: 
    Timestampable:
    Markdown:
      fields: [body]
  columns:
    title:
      type:         string(255)
      notnull:      true
    body:           clob
    list_id:        integer
    score:          
      type:         integer
      default:      0
    count:          
      type:         integer
      default:      0
    submitted_by:   
      type:         integer(4)
      notnull:      true
  relations:
    CommunityList:
      alias:            List
      foreignAlias:     Items
      local:            list_id
      onDelete:         CASCADE
    User:
      class:            sfGuardUser
      foreignAlias:     CommunityListItems
      local:            submitted_by
      

PluginReleaseSymfonyApiVersion:
  actAs:            [Timestampable]
  columns:
    release_id:
      type:         integer
      notnull:      true
    api_version_id:
      type:         integer
      notnull:      true
  relations:
    Release:
      class:        PluginRelease
      local:        release_id
      onDelete:     CASCADE
    ApiVersion:
      class:        SymfonyApiVersion
      local:        api_version_id
      onDelete:     CASCADE
      
SymfonyApiVersion:
  actAs:            [Timestampable]
  columns:
    name:
      type:             string(5)
      notnull:          true
    