SymfonyPlugin:
  actAs:                              
    Sluggable: ~
    Timestampable: ~
    myLuceneDoctrineTemplate: ~
    Commentable:  []
  columns:
    title:                            
      type:                           string(255)
      unique:                         true
      notnull:                        true
    description:                      clob
    user_id:                          integer(4)
    symfony_developer:                string(255)
    category_id:                      integer
    active:                           boolean
    repository:                       string(255)
    image:                            string(255)
    homepage:                         string(255)
    ticketing:                        string(255)
  relations:
    sfGuardUser:
      alias:                          User
      foreignAlias:                   Plugins
      local:                          user_id
    Raters:
      class:                          sfGuardUser
      refClass:                       PluginRating
      foreignAlias:                   RatedPlugins
    PluginCategory:
      alias:                          Category
      foreignAlias:                   Plugins
      local:                          category_id

PluginRating:
  actAs:    [Timestampable]
  columns:
    symfony_plugin_id:  integer
    sf_guard_user_id:    integer(4)
    rating:     integer
  relations:  
    SymfonyPlugin:
      alias:        Plugin
      foreignAlias: Ratings
      # local:        plugin_id
      onDelete:     CASCADE
    sfGuardUser:
      alias:          User
      foreignAlias:   Ratings
      # local:          user_id
      onDelete:     CASCADE        

PluginAuthor:
  columns:
    first_name:                 string(255)
    last_name:                  string(255)
    email:                      string(255)
    bio:                        clob
    sf_guard_user_id:           integer(4)
  relations:
    sfGuardUser:
      alias:                          User
      foreignAlias:                   Author
      type:                           one
      foreignType:                    one

PluginCategory:
  actAs:
    Sluggable:  ~
  columns:
    name:                       string(255)
    description:                clob

PluginRelease:
  columns:
    plugin_id:              integer
    version:                string(10)
    date:   timestamp
    symfony_version_min:
      type:                 string(10)
      # values:               [1.0, 1.1, 1.2, 1.3, 2.0]
    symfony_version_max:
      type:                 string(10)
      # values:               [1.0, 1.1, 1.2, 1.3, 2.0]
    summary:                clob
    stability:              string(30)
    readme:                 clob
    dependencies:           string(255)
  relations:
    SymfonyPlugin:
      alias:                Plugin
      foreignAlias:         Releases
      local:                plugin_id
      
      
      